# Generated by Django 3.2.6 on 2021-08-10 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ReadingFile', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='diocane',
            new_name='check',
        ),
    ]
