# Generated by Django 3.2.6 on 2021-08-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadingFile', '0002_rename_diocane_book_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='books/covers'),
        ),
    ]
