# Generated by Django 3.2.6 on 2021-08-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReadingFile', '0003_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='audiobook',
            field=models.FileField(blank=True, null=True, upload_to='books/audiobooks'),
        ),
    ]
